// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0566a1c8-30ec-43a9-84c1-2946fc61d310",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XQFLn09Jq",
    "aws_user_pools_web_client_id": "4li3v2il36jflmjbbglor4obs6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bqfyr3teqrfxnb2xbi6sy3locy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "aws-athena-query-results-scalla-prod",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
